# Task 1
# Description:
# Check the emulator sensitivity to dataset volume / modewise training / etc.

project:
  prefix: data_volume_sensitivity_p
  description: Test the keras tuner sensitivitt to the data voume.

dataset:
  file_path: ~/data/p10_all_samples_output_cleaned_shuffled.nc 
  volume_factor: 1.0
  volume_factor_effective: 0.10
  validation_split: 0.2

variables:
  input: ['tair', 'pressure', 'rh', 'wbar', 'num_aer', 'r_aer', 'kappa']
  output: ['fn']

compile:
  optimizer: "Adam" # tf.optimizers.Adam()
  loss: "mse"
  metrics: ["mae"]

RandomSearch:
  objective: "val_loss"
  overwrite: False
  executions_per_trial: 1
  max_trials: 10000
  directory: ./results

search:
  batch_size: 1024
  epochs: 100
  verbose: 2
  # callbacks: # Callbacks are written in the  


